---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: xrayvpn-auth-secret
  namespace: xrayvpn
spec:
  infisicalAuthRef:
    name: infisical-machine-identity
    namespace: infisical-operator
  sources:
    - projectId: "59f7eabf-94e5-49d0-85ed-975dfdf27f11"
      environmentSlug: prod
      secretPath: "/"
  syncOptions:
    refreshInterval: 1m
  targets:
    - name: xrayvpn-auth-secret
      namespace: xrayvpn
      kind: Secret
      creationPolicy: Owner
      secretType: Opaque
      template:
        engineVersion: v1
        data:
          XRAY_CLIENT_ID: "{{ .XRAY_CLIENT_ID.Value }}"
          XRAY_REALITY_DEST: "{{ .XRAY_REALITY_DEST.Value }}"
          XRAY_REALITY_PRIVATE_KEY: "{{ .XRAY_REALITY_PRIVATE_KEY.Value }}"
          XRAY_REALITY_SERVER_NAME: "{{ .XRAY_REALITY_SERVER_NAME.Value }}"
          XRAY_REALITY_SHORT_ID: "{{ .XRAY_REALITY_SHORT_ID.Value }}"
