apiVersion: v1
kind: Service
metadata:
  name: x-ui
  namespace: xrayvpn
spec:
  selector:
    app: x-ui
  ports:
    - name: web
      port: 2053
      targetPort: 2053
  type: ClusterIP
