apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  infisicalAuthRef:
    name: infisical-machine-identity
    namespace: infisical-operator
  sources:
    - projectId: "59f7eabf-94e5-49d0-85ed-975dfdf27f11"
      environmentSlug: prod
      secretPath: "/"
  syncOptions:
    refreshInterval: 1m
  targets:
    - name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
      kind: Secret
      creationPolicy: Owner
      secretType: Opaque
      template:
        engineVersion: v1
        data:
          admin-token: '{{ "{{" }} .GARAGE_ADMIN_TOKEN.Value {{ "}}" }}'
          garage.toml: '{{ "{{" }} .GARAGE_CONFIG_TOML.Value {{ "}}" }}'
          rpc-secret: '{{ "{{" }} .GARAGE_RPC_SECRET.Value {{ "}}" }}'
