apiVersion: v1
data:
  custom.yml: ""
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"custom.yml":""},"kind":"ConfigMap","metadata":{"annotations":{},"name":"authentik-default","namespace":"default"}}
  creationTimestamp: "2026-08-30T08:28:20Z"
  name: authentik-default
  namespace: default
  resourceVersion: "64781267"
  uid: 4acecb01-ea80-4373-ab13-6f7ef134db0d
