---
- name: Restart kanidm-unixd
  ansible.builtin.systemd:
    name: kanidm-unixd
    state: restarted
  become: true

- name: Restart kanidm-unixd-tasks
  ansible.builtin.systemd:
    name: kanidm-unixd-tasks
    state: restarted
  become: true

- name: Reload ssh
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
  become: true
