---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cloudflared-creds-fickledev
  namespace: cloudflared-fickledev
spec:
  infisicalAuthRef:
    name: infisical-machine-identity
    namespace: infisical-operator
  sources:
    - projectId: "59f7eabf-94e5-49d0-85ed-975dfdf27f11"
      environmentSlug: prod
      secretPath: "/"
  syncOptions:
    refreshInterval: 1m
  targets:
    - name: cloudflared-creds-fickledev
      namespace: cloudflared-fickledev
      kind: Secret
      creationPolicy: Owner
      secretType: Opaque
      template:
        engineVersion: v1
        data:
          token: "{{ .CLOUDFLARED_TUNNEL_TOKEN.Value }}"
