apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"ApplicationSet","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"argocd"},"name":"apps","namespace":"argocd"},"spec":{"generators":[{"git":{"directories":[{"path":"apps/*"}],"repoURL":"http://192.168.1.200:3000/giteaadmin/gitops-apps.git","revision":"HEAD"}}],"template":{"metadata":{"name":"{{path.basename}}"},"spec":{"destination":{"namespace":"{{path.basename}}","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"{{path}}","repoURL":"http://192.168.1.200:3000/giteaadmin/gitops-apps.git","targetRevision":"HEAD"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}}}
  creationTimestamp: "2026-08-30T02:39:01Z"
  generation: 1
  labels:
    argocd.argoproj.io/instance: argocd
  name: apps
  namespace: argocd
  resourceVersion: "66150898"
  uid: 26b886a7-9112-4c6c-a14d-cfd07c575770
spec:
  generators:
  - git:
      directories:
      - path: apps/*
      repoURL: http://192.168.1.200:3000/giteaadmin/gitops-apps.git
      revision: HEAD
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        namespace: '{{path.basename}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{path}}'
        repoURL: http://192.168.1.200:3000/giteaadmin/gitops-apps.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
status:
  conditions:
  - lastTransitionTime: "2026-08-31T08:27:43Z"
    message: Successfully generated parameters for all Applications
    reason: ApplicationSetUpToDate
    status: "False"
    type: ErrorOccurred
  - lastTransitionTime: "2026-08-31T08:27:43Z"
    message: Successfully generated parameters for all Applications
    reason: ParametersGenerated
    status: "True"
    type: ParametersGenerated
  - lastTransitionTime: "2026-08-31T08:27:43Z"
    message: ApplicationSet up to date
    reason: ApplicationSetUpToDate
    status: "True"
    type: ResourcesUpToDate
  resources:
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: xrayvpn
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: garage
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: postgres
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: cert-manager
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: home-assistant
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: base
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: cluster-issuer
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: reloader
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: infisical-operator
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: cnpg-operator
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: kubernetes-dashboard
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: common
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: cloudflared-fickledev
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: minecraft-bedrock
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: mailu
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: authentik-fickledev
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: argocd
    namespace: argocd
    status: Synced
    version: v1alpha1
  - group: argoproj.io
    health:
      status: Healthy
    kind: Application
    name: reflector
    namespace: argocd
    status: Synced
    version: v1alpha1
