target_hosts:
  vars:
    ansible_user: tochi
    ansible_ssh_private_key_file: ~/.ssh/hp-z440
  hosts:
    n100:
      ansible_host: 192.168.1.10
      ansible_user: root
    hp-z440:
      ansible_host: 192.168.1.2
      ansible_user: root
    # frontier:
    #   ansible_host: 192.168.1.3
    #   ansible_user: root
    k3s-server:
      ansible_host: 192.168.1.150
    k3s-agent-minipc:
      ansible_host: 192.168.1.151
    k3s-agent-z440:
      ansible_host: 192.168.1.152
    # k3s-agent-frontier:
    #   ansible_host: 192.168.1.153
    nas:
      ansible_host: 192.168.1.201
    gitea:
      ansible_host: 192.168.1.200
      ansible_user: root
    pbs:
      ansible_host: 192.168.1.202
      ansible_user: root
    vps:
      ansible_host: 100.109.6.7
      ansible_user: trvlr

proxmox_nodes:
  hosts:
    n100: {}
    hp-z440: {}
    frontier: {}

vms:
  hosts:
    k3s-server: {}
    k3s-agent-minipc: {}
    k3s-agent-z440: {}
    k3s-agent-frontier: {}
    nas: {}

containers:
  hosts:
    gitea: {}
    pbs: {}

vps:
  hosts:
    vps: {}

k3s:
  hosts:
    k3s-server: {}
    k3s-agent-minipc: {}
    k3s-agent-z440: {}
    k3s-agent-frontier: {}
