apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert/certificate.yaml
  - unbound/unbound.yaml
  - patch/mailu-front-service.yaml
  - patch/remove-backend-protocol-ingress.yaml

# Keep values.yaml for Helm values; this kustomization only aggregates supporting manifests
 
patchesStrategicMerge:
  - patch/add-admin-ingress-path.yaml

