---
- name: Fetch k3s kubeconfig to control node
  hosts: k3s
  gather_facts: false
  become: true
  vars:
    kubeconfig_name: "{{ k3s_kubeconfig_target | default('k3s') }}"
    local_kube_dir: "{{ lookup('env','HOME') + '/.kube' }}"
    dest_path: "{{ local_kube_dir + '/config-' + kubeconfig_name }}"
  tasks:
    - name: Ensure local .kube exists
      become: false
      ansible.builtin.file:
        path: "{{ local_kube_dir }}"
        state: directory
        mode: "0700"
      delegate_to: localhost

    - name: Fetch k3s kubeconfig from remote master
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ dest_path }}"
        flat: true
      run_once: true
      become: true
