---
- name: Setup external storage on k3s agent
  hosts: k3s-agent-z440
  become: true
  roles:
    - role: storage_disk
      vars:
        storage_disk_items: "{{ agent_data_disks | default([]) }}"
