---
- name: Setup external storage on k3s agent
  hosts: k3s-agent-z440
  become: true
  tasks:
    - name: Ensure storage prerequisite packages are installed
      ansible.builtin.apt:
        name:
          - parted
          - xfsprogs
        state: present
        update_cache: yes

    - name: Configure data disks
      ansible.builtin.include_tasks: configure_scsi_disk.yml
      loop: "{{ agent_data_disks | default([]) }}"
      loop_control:
        loop_var: disk_item
