---
# Top-level site playbook to run multiple component playbooks
- name: Run connectivity checks
  import_playbook: ping.yml

- name: Configure NAS host
  import_playbook: nas.yml

# Add other component playbooks below when available
# - import_playbook: k3s.yml
- import_playbook: gitea.yml
- name: Configure PBS host
  import_playbook: pbs.yml

- name: Ensure certificates on NAS and distribute to VPS
  import_playbook: letsencrypt.yml

- name: Configure cert-manager certificates for k3s
  import_playbook: cert_manager.yml

# VPS reverse proxy
- name: Configure VPS reverse proxy
  import_playbook: vps.yml

- import_playbook: proxmox_backup.yml
