apiVersion: v1
data:
kind: Secret
metadata:
  creationTimestamp: "2026-03-07T19:46:11Z"
  name: argocd-initial-admin-secret
  namespace: argocd
  resourceVersion: "32212"
  uid: 15c46a22-c72b-4206-b1b1-a1820d4a5871
type: Opaque
