server {
    listen 80;
    server_name fickledev.com www.fickledev.com;

    return 301 https://$host$request_uri;
}

server {
    listen 80;
    server_name *.fickledev.com;

    return 403;
}

server {
    listen 127.0.0.1:8443 ssl http2;
    server_name www.fickledev.com;

    ssl_certificate /etc/letsencrypt/live/fickledev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fickledev.com/privkey.pem;

    client_max_body_size 256M;

    location / {
        proxy_pass http://192.168.1.103:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /blog/ {
        rewrite ^/blog/(.*)$ /$1 break;
        proxy_pass http://192.168.1.101:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;

        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Original-Host $http_host;
    }

    location = /blog {
        return 301 /blog/;
    }
}

server {
    listen 127.0.0.1:8443 ssl http2;
    server_name fickledev.com;

    ssl_certificate /etc/letsencrypt/live/fickledev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fickledev.com/privkey.pem;

    return 301 https://www.fickledev.com$request_uri;
}

server {
    listen 127.0.0.1:8443 ssl http2;
    server_name *.fickledev.com;

    ssl_certificate /etc/letsencrypt/live/fickledev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fickledev.com/privkey.pem;

    return 403;
}
