apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config-template
  namespace: xrayvpn
data:
  config.json.tpl: |
    {
      "log": {
        "loglevel": "warning"
      },
      "inbounds": [
        {
          "port": 443,
          "protocol": "vless",
          "settings": {
            "clients": [
              {
                "id": "${XRAY_CLIENT_ID}",
                "flow": "xtls-rprx-vision",
                "level": 0
              }
            ],
            "decryption": "none"
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "show": false,
              "dest": "${XRAY_REALITY_DEST}",
              "xver": 0,
              "serverNames": [
                "${XRAY_REALITY_SERVER_NAME}"
              ],
              "privateKey": "${XRAY_REALITY_PRIVATE_KEY}",
              "shortIds": [
                "${XRAY_REALITY_SHORT_ID}"
              ]
            }
          },
          "sniffing": {
            "enabled": true,
            "destOverride": [
              "http",
              "tls",
              "quic"
            ]
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
