apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/infisical-common
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - infisical-cnpg-garage-backup.yaml
  - infisical-postgres-credentials.yaml
  - backups.yaml
