---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  infisicalAuthRef:
    name: infisical-machine-identity
    namespace: infisical-operator
  sources:
    - projectId: "59f7eabf-94e5-49d0-85ed-975dfdf27f11"
      environmentSlug: prod
      secretPath: "/"
  syncOptions:
    refreshInterval: 1m
  targets:
    - name: postgres-credentials
      namespace: postgres
      kind: Secret
      creationPolicy: Owner
      secretType: Opaque
      template:
        engineVersion: v1
        data:
          POSTGRES_DB: "{{ .POSTGRES_DB.Value }}"
          POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD.Value }}"
          POSTGRES_USER: "{{ .POSTGRES_USER.Value }}"
