apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-cloudflared
spec:
  podSelector:
    matchLabels:
      app: authentik
  ingress:
    - from:
        - namespaceSelector: {}
  policyTypes:
    - Ingress
